//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public long CustomerID { get; set; }
        public string Address { get; set; }
        public Nullable<long> MobileNo { get; set; }
        public byte[] Photo { get; set; }
        public byte[] IdCard { get; set; }
        public string IdCardNo { get; set; }
        public string CustomerName { get; set; }
        public string PartyGST { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
