//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public string RoomNo { get; set; }
        public string RoomType { get; set; }
        public decimal Rate { get; set; }
    
        public virtual ICollection<TimeTable> TimeTables { get; set; }
    }
}
