//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMSAPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public long TimeTableID { get; set; }
        public Nullable<System.DateTime> CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutTime { get; set; }
        public long CustomerID { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> PickUpandDrop { get; set; }
        public Nullable<decimal> Laundry { get; set; }
        public Nullable<decimal> Bevrages { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<bool> GST { get; set; }
        public Nullable<decimal> Food { get; set; }
        public Nullable<decimal> MiniBite { get; set; }
        public long InvoiceNo { get; set; }
        public string SessionName { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
